# Generated by Django 3.2.4 on 2021-06-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
